### ISSUE TITLE
path

### ISSUE THREAD

**Issue by tcpipchip** [fcgdam/zLorawan_Node#1]
Hi
Where path i make the git ?
because when i compile it didnt find the zephyr.h and lorawan.h
![image](https://user-images.githubusercontent.com/11488460/199813913-6392a0d6-7479-4c78-97c3-fc5016c12ea2.png)
Thanks

**Comment by tcpipchip** [comment]
![image](https://user-images.githubusercontent.com/11488460/199814102-cbb66a4c-1bde-4db2-8807-2fa0a98242f8.png)
![image](https://user-images.githubusercontent.com/11488460/199814356-136e754f-fde1-44af-8a94-47d479c10971.png)

**Comment by fcgdam** [comment]
You are probably using Zephyr 3.2.99, check the VERSION file under the zephyr folder.
The code is for Zephyr 3.1.99, but you can convert it by changing the includes to: 
```
#include <zephyr/lorawan/lorawan.h>
#include <zephyr/kernel.h>
#include <zephyr/usb/usb_device.h>
#include <zephyr/drivers/uart.h>
#include <zephyr/drivers/gpio.h>

```
Check also the example under the **samples/subsys/lorawan/class_a** to see the correct paths if needed.

**Comment by tcpipchip** [comment]
thanks for you help
Can you help again ?
![image](https://user-images.githubusercontent.com/11488460/199960013-df634f55-f462-494d-8e67-12a7dafc7426.png)

**Comment by fcgdam** [comment]
What is your compile command?
For what board are you compiling?
Did you create an overlay file for your board with the radio specifications? Check the boards/blackpill_f411ce.overlay file, for example.

**Comment by tcpipchip** [comment]
west build -p always -b b_l072z_lrwan1 zLorawan_Node
B-L072Z-LRWAN1
well, i dont know about that...it´s a long time that i didnt work with overlay without use IDE...
Can you access my machine ?
I am testing on WSL2

**Comment by fcgdam** [comment]
Hi, I've compiled for the b_l072z_lrwan1 board without any issue. So it might be your environment, and sorry, don't use Windows or WSL2 so can't help with that.

**Comment by tcpipchip** [comment]
can you send the command that you use ?
Are you using IDE or line command enviroment ?
On Linux or VM ?
Thanks

**Comment by fcgdam** [comment]
The same command line (no IDE) that you used, but on 100% Linux. No emulation on Windows (WSL).

Try to compile first the examples from the zephyr folder since the issue is with your environment, not with this repository.

**Comment by tcpipchip** [comment]
yes, the examples compiles.
Where folder i tar (git) you github source ? Maybe this is the problem
thanks to the help

**Comment by tcpipchip** [comment]
did you already got this error ?
![image](https://user-images.githubusercontent.com/11488460/200183225-24bf927b-ec2d-4e87-8b8e-82753284810c.png)
